name: locationprojectflutter
description: A new Flutter application.

version: 1.0.0+19

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  latlong: ^0.6.1
  google_maps_flutter: ^0.5.26
  location: ^3.0.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  cached_network_image: ^2.2.0
  flutter_slidable: ^0.5.4
  share: ^0.5.3
  grouped_buttons: ^1.0.4
  fluttertoast: ^3.1.3
  chewie: ^0.9.10
  image_picker: ^0.6.7+2
  photo_view: ^0.5.0
  intl: ^0.16.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.15
  firebase_storage: ^3.0.6
  google_sign_in: ^4.0.0
  flutter_facebook_login: ^3.0.0
  auto_animated: ^2.1.0
  map_launcher: ^0.4.5
  flutter_geofence: ^0.2.0
  flutter_local_notifications: ^1.4.3
  flutter_instagram_stories: ^0.1.3+4
  simple_image_crop: ^0.1.3
  path_provider: ^1.1.0
  audioplayers: ^0.13.2
  audioplayer: ^0.8.1
  permission_handler: ^3.0.0
  agora_rtc_engine: ^1.0.13
  provider: ^4.0.5+1
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
#  get_it: ^3.1.0
#  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4
  flutter_audio_recorder: ^0.5.5
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/google_icon.png
    - assets/img_not_available.jpeg
    - assets/mimi1.gif
    - assets/mimi2.gif
    - assets/mimi3.gif
    - assets/mimi4.gif
    - assets/mimi5.gif
    - assets/mimi6.gif
    - assets/facebook_icon.jpg
    - assets/phone_icon.jpg